name: Pull request workflow
on: push
env:
  BUCKET_NAME: care-bff
  AWS_REGION: us-east-1
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Cache node modules
        id: node-module-cache
        uses: ./.github/actions/cache-deps
        with:
          caching: false

      - name: Build
        run: npm run build:fe

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        # https://www.udemy.com/course/github-actions-the-complete-guide/learn/lecture/34140726#overview
        with:
          role-to-assume: arn:aws:iam::682755029646:role/serverless-deploy-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to s3
        run: aws s3 sync ./dist/apps/fe s3://${{env.BUCKET_NAME}} --region ${{env.AWS_REGION}}

      - name: Install Serverless globally
        run: npm i -g serverless

      - name: Deploy Bff to serverless
        run: serverless deploy

      - name: print the data
        run: echo "successfully uploaded"
